---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "SMS-Tools"
keywords:    "SMS-Tools, sms, mms, iphone, android, messages, iMessage, text"
description: "Multipurpose import / export / merge tool for your text message history."
source_link: "https://github.com/t413/SMS-Tools"
favicon:
touch_icon:
google_analytics_key: UA-49607422-1


### template colors, used site-wide via css ###
colors:
  black:
    light: '#303030'
    dark: '#111111'
  white:
    light: '#f5f5f5'
    dark: '#f8f8f8'
  red:
    light: '#DA4C47'
    dark: '#CC4A45'
  blue:
    light: '#689DD6'
    dark: '#4895E8'
  purple:
    light: '#C67ADD'
    dark: '#B167C7'
  green:
    light: '#a3d832'
    dark: '#9bcf2f'
  orange:
    light: '#faaf22'
    dark: '#fab125'
  turquoise:
    light: '#0fbfcf'
    dark: '#0fbfcf'
